### ISSUE TITLE
Demo pivotal tracker account

### ISSUE THREAD

**Issue by mayra-cabrera** [GoBootcamp/clirescue#6]
Hi,

If I try to use "gobootcamp" account I get the following response

``` bash
Username: gobootcamp
Password: 
API response: 
{"code":"invalid_authentication","kind":"error","error":"Invalid authentication credentials were presented.","possible_fix":"Recheck your name (email address or Tracker username) and password."}
```

Looks like the credentials are invalid. Do you have any other account that we can use? 

Thanks!

**Comment by daplho** [comment]
uname: i786504
email: i786504@mvrht.com
pswrd: qwerty123

**Comment by mayra-cabrera** [comment]
thanks @daplho
